name: Deploy to Scaleway

on:
  push:
    branches:
      - master

env:
  SCALEWAY_PROJECT_ID: 134da729-a2d5-4346-afaa-6e494eb52961

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}

      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud
          username: nologin
          password: ${{ secrets.SCALEWAY_SECRET_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: rg.fr-par.scw.cloud/${{ env.SCALEWAY_PROJECT_ID }}/second-brain:latest 